/* eslint-disable react-refresh/only-export-components -- exports the
   BEFORE_AFTER_ASSET config + BeforeAfterAsset type alongside the
   component, same accepted pattern as src/lib/auth.tsx */
import { useEffect, useState } from 'react';

/**
 * Homepage "before/after" proof section — see docs/validation/HOMEPAGE.md
 * for the original requirement and reasoning.
 *
 * `BEFORE_AFTER_ASSET` now points at a REAL asset pair, generated by
 * actually running Rampcut's own export math (curveToFFmpegFilter +
 * buildAtempoFilters, copied verbatim from src/lib/curveMath.ts and
 * src/lib/ffmpegBridge.ts) against the real "Hero Moment" preset
 * (src/content/curves.mjs) and the real procedural demo clip
 * (scripts/generate-demo-clip.sh's output — itself fully synthetic ffmpeg
 * lavfi generation, explicitly labeled in-frame, no footage/licensing
 * question), executed via a system ffmpeg CLI rather than ffmpeg.wasm in a
 * browser (this session's environment has no real browser to drive) —
 * same filter graph, same libx264/aac encode settings the app's own
 * ffmpegWorker.ts "simple path" uses, so the output is what the real
 * pipeline actually produces for this preset, not an approximation.
 * `presetLabel` matches DropZone.tsx's `DEMO_PRESET` (heroMoment) so
 * "try it yourself" opens with the same curve shown here.
 */

export interface BeforeAfterAsset {
  available: boolean;
  beforeVideoSrc?: string;
  afterVideoSrc?: string;
  beforePosterSrc?: string;
  afterPosterSrc?: string;
  /** The exact preset used to produce afterVideoSrc — must match
   *  DropZone.tsx's DEMO_PRESET so the "try it yourself" demo project opens
   *  with the same curve shown here. See presets.ts for available presets. */
  presetLabel?: string;
}

export const BEFORE_AFTER_ASSET: BeforeAfterAsset = {
  available: true,
  beforeVideoSrc: '/demo/sample-clip.mp4',
  afterVideoSrc: '/demo/hero-moment-after.mp4',
  beforePosterSrc: '/demo/before-poster.jpg',
  afterPosterSrc: '/demo/after-poster.jpg',
  presetLabel: 'Hero Moment',
};

function usePrefersReducedMotion(): boolean {
  // Computed as the INITIAL state value (lazy useState initializer) rather
  // than set from inside an effect — avoids both an unnecessary extra
  // render on mount and a synchronous setState-in-effect lint violation.
  // The effect below only ever updates it from a real async event callback.
  const [reduced, setReduced] = useState(() => {
    if (typeof window === 'undefined' || !window.matchMedia) return false;
    return window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  });
  useEffect(() => {
    if (typeof window === 'undefined' || !window.matchMedia) return;
    const mq = window.matchMedia('(prefers-reduced-motion: reduce)');
    const onChange = (e: MediaQueryListEvent) => setReduced(e.matches);
    mq.addEventListener('change', onChange);
    return () => mq.removeEventListener('change', onChange);
  }, []);
  return reduced;
}

export function BeforeAfterDemo({ asset = BEFORE_AFTER_ASSET }: { asset?: BeforeAfterAsset }) {
  const prefersReducedMotion = usePrefersReducedMotion();

  if (!asset.available || !asset.beforeVideoSrc || !asset.afterVideoSrc) {
    return null;
  }

  return (
    <section style={{ padding: '32px 24px 80px' }}>
      <div style={{ maxWidth: 1200, margin: '0 auto' }}>
        <p
          style={{
            margin: '0 0 20px',
            fontSize: 12,
            fontWeight: 600,
            textTransform: 'uppercase',
            letterSpacing: '0.1em',
            color: 'var(--color-clay-pink)',
            textAlign: 'center',
          }}
        >
          A real export{asset.presetLabel ? ` — "${asset.presetLabel}" preset` : ''}
        </p>
        <div
          className="clay-shadow"
          style={{
            display: 'grid',
            gridTemplateColumns: '1fr 1fr',
            gap: 2,
            borderRadius: 20,
            overflow: 'hidden',
            border: '1px solid var(--color-clay-line)',
          }}
        >
          {[
            { label: 'Before', src: asset.beforeVideoSrc, poster: asset.beforePosterSrc },
            { label: 'After',  src: asset.afterVideoSrc,  poster: asset.afterPosterSrc },
          ].map(({ label, src, poster }) => (
            <div key={label} style={{ position: 'relative', background: '#000' }}>
              <video
                src={src}
                poster={poster}
                // Reduced motion: show only the poster frame, never autoplay.
                autoPlay={!prefersReducedMotion}
                loop={!prefersReducedMotion}
                muted
                playsInline
                controls={prefersReducedMotion}
                style={{ width: '100%', display: 'block', aspectRatio: '16 / 9', objectFit: 'cover' }}
              />
              <span
                style={{
                  position: 'absolute',
                  top: 12,
                  left: 12,
                  padding: '4px 10px',
                  borderRadius: 999,
                  background: 'rgba(10,10,10,0.55)',
                  color: '#fff',
                  fontSize: 11,
                  fontWeight: 600,
                  letterSpacing: '0.04em',
                  textTransform: 'uppercase',
                }}
              >
                {label}
              </span>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
